#!/usr/bin/env python3
"""Generate XOR-obfuscated C arrays for Talon Config.h transport strings.

Usage: python3 gen_config.py
Prints C code to paste into Agent/Include/Config.h (regenerate per build lot;
the key is random each run).
"""
import secrets


def encode(text: str) -> tuple[bytes, bytes]:
    raw = text.encode("utf-16-le") + b"\x00\x00"  # null-terminated wide string
    key = secrets.token_bytes(16)
    out = bytes(b ^ key[i % 16] for i, b in enumerate(raw))
    return out, key


def c_array(name: str, data: bytes) -> str:
    lines = [f"static const UCHAR {name}[ {len(data)} ] = {{"]
    rows = []
    for i in range(0, len(data), 12):
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 12]))
    lines.append(",\n".join(rows))
    lines.append("};")
    return "\n".join(lines)


UA = r"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
HOST = "192.168.0.251"
ENDPOINT = "index.php"

ua_data, ua_key = encode(UA)
host_data, host_key = encode(HOST)
ep_data, ep_key = encode(ENDPOINT)

print("// --- generated by tools/gen_config.py (do not edit by hand) ---")
print(c_array("CfgUaKey", ua_key))
print(c_array("CfgUaXor", ua_data))
print(c_array("CfgHostKey", host_key))
print(c_array("CfgHostXor", host_data))
print(c_array("CfgEpKey", ep_key))
print(c_array("CfgEpXor", ep_data))
print(f"// sizes: CfgUaXor={len(ua_data)} CfgHostXor={len(host_data)} CfgEpXor={len(ep_data)}")
